# Travis-CI build script for KaHyPar

language: cpp

# Ubuntu 14.04 Trusty support
sudo: required
dist: trusty

addons:


matrix:
  include:
    # gcc 6 - Debug Build
    - env: CMAKE_CC="gcc-6" CMAKE_CXX="g++-6" BUILD_TYPE="Debug" COMPILER_FLAGS=""
      os: linux
      addons: &gcc6
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - cmake-data
            - g++-6
            - libboost-program-options1.55.0
            - libboost-program-options1.55-dev
        sonarqube:
          organization: "sebastianschlag-github"
          token:
            secure: "Zagex1M0oD8ktkLUdRkNcfW2gni0gvr2WeC0rcjmjzw/kEGEnvsaAQHBob2jz38Hhxtr9IDeMpTKdqCFBuCYbEAQqeq2PSIRhv7yQa4WEzcG/IRWUzoGRYJ6McIh2tYHXT7DxMuZ6Fnt6X1Or4d9eCtpWlAzShvHalLQhXXjnaCeq7rDVL1UARQtB6Tc73U57yIMDLqZrCX0S0SkVFKb0o/xfuLHgwyZ3QOg34hxw04sGBogaHjhVoTNgKAb0/DEYAZRNHa0ztxbC6k6G8uE52g09ZXLb/u2Y/WZSTYXv6uuqi8ZYtrqryVwDy3TSIKwGptQkR2CpghqRLKAFSgDs1rBSiUQ3fVOMcF5+mY4oN9DgGPDZy8oDphqEJh4EEr0XAS9lgt5Gmrusmyliyf0qJTQu99gQsJ50sRRSpYqygyIf59fN58mu5x0lGbG46qVzDKtn46ysRX3Vqb5sbgIfLmjEdhJCitRwHNJlKvppr7AfWEHkrk36qIQKgiQnSObb0xPS+a9F2MwCD9e+p2xAXvK2lyJ+Dlf5Hoj+ToKNz0IUXi1bLQfBwXdIGgqgB6LTh7pz9E9ArLMqFWZ+c1kr9vLw3m4XlUV+MuOOwKYjpV0PilR2tU7aPDLznn7T+0wiAXVf09CCNv+v4vzDtOsasPlvuQRwp4MEqpPl4q8jz0="

    # gcc 6 - Release Build
    - env: CMAKE_CC="gcc-6" CMAKE_CXX="g++-6" BUILD_TYPE="Release" COMPILER_FLAGS=""
      os: linux
      addons: *gcc6

      # gcc 6 - RelWithDebInfo Build - end to end tests
    - env: CMAKE_CC="gcc-6" CMAKE_CXX="g++-6" BUILD_TYPE="RelWithDebInfo" COMPILER_FLAGS=""
      os: linux
      addons: *gcc6

    # clang 3.7 on MacOSX
    - env: CMAKE_CC="clang" CMAKE_CXX="clang++" BUILD_TYPE="Debug" COMPILER_FLAGS=""
      os: osx

    - env: CMAKE_CC="clang" CMAKE_CXX="clang++" BUILD_TYPE="Release" COMPILER_FLAGS=""
      os: osx

before_script:
  # print out some version numbers
  - $CMAKE_CXX --version
  - cmake --version

  # configure
  - mkdir build; cd build
  - cmake
      -DCMAKE_BUILD_TYPE="$BUILD_TYPE"
      -DCMAKE_C_COMPILER="$CMAKE_CC" -DCMAKE_CXX_COMPILER="$CMAKE_CXX"
      -DCMAKE_C_FLAGS="$COMPILER_FLAGS" -DCMAKE_CXX_FLAGS="$COMPILER_FLAGS"
      $CMAKE_ARGS ..

script:
  - |
    if [[ "$BUILD_TYPE" == "RelWithDebInfo" && "$CMAKE_CXX" == "g++-6" ]]; then
      build-wrapper-linux-x86-64 --out-dir bw-output make integration_tests;
    else
      build-wrapper-linux-x86-64 --out-dir bw-output make -j4;
    fi
  - sonar-scanner

cache:
  directories:
    - '$HOME/.sonar/cache'
