version: 1.0.{build}
image: Visual Studio 2015
environment:
  BOOST_ROOT: C:\Libraries\boost_1_59_0
  BOOST_LIBRARYDIR: C:\Libraries\boost_1_59_0\lib64-msvc-14.0
before_build:
- ps: (new-object net.webclient).DownloadFile(
        "https://download.microsoft.com/download/D/7/B/D7BBA00F-71B7-436B-80BC-4D22F2EE9862/MSMpiSetup.exe",
        "C:\projects\MSMpiSetup.exe")
- ps: (new-object net.webclient).DownloadFile(
        "https://download.microsoft.com/download/D/7/B/D7BBA00F-71B7-436B-80BC-4D22F2EE9862/msmpisdk.msi",
        "C:\projects\msmpisdk.msi")
- C:\projects\MSMpiSetup.exe -unattend -minimal
- set PATH=C:\Program Files\Microsoft MPI\Bin;%PATH%
- echo %path%
- msiexec.exe /quiet /qn /i C:\projects\msmpisdk.msi
- set MSMPI
        
- cmd: >-
    echo Getting submodules


    git submodule update --init --recursive


    echo Running cmake...


    cd C:\projects\kahypar-vr7q9


    md build


    cd build


    cmake -G "Visual Studio 14 Win64" -DBoost_USE_STATIC_LIBS="ON" -DBoost_USE_STATIC_RUNTIME="ON" ..
build:
  project: C:\projects\kahypar-vr7q9\build\KaHyPar.sln
  parallel: true
  verbosity: normal
